# Introduction to Tensors

In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [3]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scaler.ndim

0

In [5]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant(
    [[10,7],
    [2,9]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  9]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10,7],
                             [3,2],
                             [8,9]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
# Tensors
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

![alt text](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

# Changeable Tensors `tf.Variable()`

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Will Show Error
#changeable_tensor[0] = 7
#changeable_tensor

In [15]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Creating Random Tensors

In [16]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2)) # Creating Tensors from Normal Distribution

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

# Other ways to make Tensors

In [17]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [18]:
tf.zeros(shape=(3,2),dtype = tf.int64)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]])>

## Converting Numpy Array to Tensors

In [19]:
import numpy as np
numpy_array = np.arange(1,25,dtype = np.int32) # Numpy Array Between 1 and 25
tensor_A = tf.constant(numpy_array,shape = [2,4,3])
numpy_array, tensor_A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

# Getting Information from Tensors

In [20]:
rank4_tensor = tf.zeros(shape = (2,3,4,5))
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
rank4_tensor.shape

TensorShape([2, 3, 4, 5])

In [22]:
rank4_tensor.ndim

4

In [23]:
tf.size(rank4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

#### You can also index tensors just like Python Lists

In [24]:
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [25]:
rank4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [26]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

# Manipulating Tensors

### Basic Operations

In [27]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [28]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [29]:
tensor * 11

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110,  77],
       [ 33,  44]], dtype=int32)>

In [30]:
# Another Method
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [31]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [32]:
# Matix Multiplication
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [33]:
# Also can use this
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

# Changing datatype of Tensors

In [34]:
B = tf.constant([1.7,7.4])
C = tf.constant([1,7])
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [35]:
B = tf.cast(B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [36]:
C = tf.cast(C, dtype = tf.float16)
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>

#  Finding the min, max, mean, sum

In [37]:
E = tf.constant(np.random.randint(low = 0, high = 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([65, 65, 52, 33, 24,  4, 87, 45, 78, 45, 51, 61, 13, 89, 74, 97, 89,
       21, 86, 15, 51, 62, 35, 45,  4, 78, 58, 32, 34, 20, 54, 27, 32, 39,
        0, 77, 20, 81, 71, 18, 11, 59, 90, 89, 38,  0, 75, 32, 62, 34])>

In [38]:
tf.reduce_min(E) 

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [39]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [40]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [41]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2422>

In [42]:
# Find the maximum element Position
print(tf.argmax(E))
# Find the Position of Minimum Element
print(tf.argmin(E))

tf.Tensor(15, shape=(), dtype=int64)
tf.Tensor(34, shape=(), dtype=int64)


In [43]:
print(f"The maximum value of E is at position: {tf.argmax(E).numpy()}") 
print(f"The maximum value of E is: {tf.reduce_max(E).numpy()}") 
print(f"Using tf.argmax() to index E, the maximum value of E is: {E[tf.argmax(E)].numpy()}")
print(f"Are the two max values the same (they should be)? {E[tf.argmax(E)].numpy() == tf.reduce_max(E).numpy()}")

The maximum value of E is at position: 15
The maximum value of E is: 97
Using tf.argmax() to index E, the maximum value of E is: 97
Are the two max values the same (they should be)? True


# Squeezing a tensor

In [44]:
# Creating a rank 5 (5 dimension) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0,100,50),shape = (1,1,1,1,50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [45]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

# One-Hot Encoding

In [46]:
some_list = [0,1,2,3]

# One hot encode them
tf.one_hot(some_list,depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [47]:
tf.one_hot(some_list, depth=4, on_value="We'r live !", off_value = "offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We'r live !", b'offline', b'offline', b'offline'],
       [b'offline', b"We'r live !", b'offline', b'offline'],
       [b'offline', b'offline', b"We'r live !", b'offline'],
       [b'offline', b'offline', b'offline', b"We'r live !"]], dtype=object)>

# Squaring, log, square root

In [48]:
H = tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [49]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [50]:
H = tf.cast(H, dtype = tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [51]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [52]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Manupulating `tf.Variable` tensors

In [53]:
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [54]:
I.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [55]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

# Tensors and Numpy

In [57]:
J = tf.constant(np.array([3.0,7.0,10.0]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [59]:
# Convert Tensors to Numpy
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [60]:
# Convert tensors J to numpy with .numpynumpy_array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

# Using `@tf.function`

In [64]:
# Creating a Simple Function

def function(x,y):
    return x**2 + y

x = tf.constant(np.arange(0,10))
y = tf.constant(np.arange(10,20))
function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [65]:
# Creating same function and decorate it with tf.function

@tf.function
def tf_function(x,y):
    return x**2 + y 
tf_function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

# Finding access to GPUs

In [66]:
print(tf.config.list_physical_devices("GPU"))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [67]:
!nvidia-smi

Tue Mar  1 08:25:52 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   45C    P0    28W /  70W |  14060MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------